version: "3.8"

name: demo-jenkins

services:
  app:
    container_name: jenkins-spring-boot
    build:
      context: .
      dockerfile: ./DockerFile
    restart: always
    ports:
      - "7200:7200"
    depends_on:
      - mysql
    networks:
      - java-app

  mysql:
    container_name: jenkins-mysql
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: jenkins_user
      MYSQL_USER: jenkins
      MYSQL_PASSWORD: 1234
    ports:
      - "3037:3036"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - java-app


volumes:
  mysql-data:
networks:
  java-app:
    name: java-app